### ISSUE TITLE
Known languages and tools order

### ISSUE THREAD

**Issue by Creerio** [SkyWors/SkyWors#1]
### Role

I read your bio, kinda like anyone I guess.

### Question/Suggestion

As of now, the "Know languages and tools" looks like this : 

![image](https://user-images.githubusercontent.com/44642117/179364141-b16a1076-1a6e-492d-9224-2bb3ece5ed82.png)

Usually, the order to follow is most used/regularly used on the left side, less on the right. Does it follow that order? If not, would it not be nicer to follow it? Or add a way to know that?

### Benefit

Allows anyone to know your language of predilection

**Comment by SkyWors** [comment]
Done.
